local m = peripheral.wrap("back")
m.setBackgroundColor(colors.lightBlue)
m.clear()
m.setTextColor(colors.white)
m.setTextScale(5)
m.setCursorPos(2,2)
m.write("Välkommen till")
m.setCursorPos(2,3)
m.write("Hello World!")

